application:
    jwt:
        secretKey: "securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure"
        tokenPrefix: "Bearer "
        tokenExpirationAfterDays: 7